### ISSUE TITLE
Make breakout board pass-through?

### ISSUE THREAD

**Issue by blackbit42** [tomstorey/c1600re#3]
The idea of an breakout board is brilliant!
Have you considered adding another connector to be board to make it pass-through for existing WIC modules?
I'd think that would add analysis capabilities without taking away any usefulness of the board as it is now.
Sourcing the connector would probably be a bit of a challenge, or is the connector similar enough to PCMCIA that you could adapt one with a bit of dremel butchery? I haven't checked if the pin distances match though.

**Comment by tomstorey** [comment]
That is certainly an interesting idea I had not thought of! I havent really considered trying to re-use any existing WICs since they are all for WAN technologies that are perhaps a bit beyond the average hobbyist - certainly beyond my interests from a hobby point of view anyway. :-)

The female WIC connector (on the card itself) is 68 pin with a pitch of 1.27mm which I believe is fairly standard. There should be plenty of options for the male socket that would allow another card to be plugged in as an extension. A quick search of RS shows there are some available for less than £20 with guides for support as well. It would not be too much of a stretch to design something with both headers and a socket.

**Comment by blackbit42** [comment]
Cool, I am glad you like the idea.

By the way, would you happen to know if this will work for HWIC and EHWIC cards as well? I would assume yes...

**Comment by tomstorey** [comment]
HWIC, no. It has a physically different connector with an extra row of pins. A HWIC slot can be backwards compatible with WIC, bit a WIC slot cannot be forwards compatible with HWIC.

I don't believe I've seen an EHWIC in person yet, but presumably it would also be incompatible.

**Comment by tomstorey** [comment]
Having said that, the signals within the traditional footprint are very likely the same since there is some backwards compatibility (or they do something funky with remapping pins), so if you were able to find a way to get the card to slot in you might be able to probe around, but if the HWIC needed any of those additional signals to function then you'd be out of luck.
